env:
  TERM: "xterm-256color"
  WINIT_HIDPI_FACTOR: "2.25"
  WINIT_X11_SCALE_FACTOR: '1.0'

window:
  padding:
    x: 0
    y: 0

font:
  normal:
    family: Hack
    style: Regular
  bold:
    family: Hack
    style: Bold
  italic:
    family: Hack
    style: Italic
  bold_italic:
    family: Hack
    style: Bold Italic
  size: 12
  offset:
    x: 0
    y: 3

scrolling:
  history: 10000
  multiplier: 100
  faux_multiplier: 100
  auto_scroll: true

colors:
  # Default colors
  primary:
    background: '0x1d2021'
    foreground: '0xd5c4a1'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1d2021'
    cursor: '0xd5c4a1'

  # Normal colors
  normal:
    black:   '0x1d2021'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xd5c4a1'

  # Bright colors
  bright:
    black:   '0x665c54'
    red:     '0xfe8019'
    green:   '0x3c3836'
    yellow:  '0x504945'
    blue:    '0xbdae93'
    magenta: '0xebdbb2'
    cyan:    '0xd65d0e'
    white:   '0xfbf1c7'

draw_bold_text_with_bright_colors: false 
